-- 版 4: 片付け・戻しの通知が、どの操作を指しているかを持つ
--
-- public に積む archive の通知から、その場で戻せるようにするための列。
--
-- 【archived_seq との違い】
--   archived_seq     … その行自身が片付けられた操作の番号。NULL なら生きている
--   ref_archived_seq … その行が「話題にしている」操作の番号。通知にだけ入る
--
-- 同じ archives.archived_seq を指すが、意味が逆である。archived_seq は
-- 「私は片付けられた」、ref_archived_seq は「私は片付けを知らせている」。
--
-- 【本文から拾わない理由】
--   通知の本文は --description で書き換えられる。番号が入る保証が無く、
--   人が書き換えれば壊れる。本文の形を仕様にすると、文言を直すたびに
--   画面が動かなくなる。列で持てば本文と切り離せる。
--
-- 列の追加は ALTER TABLE で足りる。テーブルの作り直しは要らない。
--
-- 当て済みの環境では二度と実行されない。書き換えてはいけない
-- （指紋が食い違い、起動が止まる）。

ALTER TABLE messages ADD COLUMN ref_archived_seq INTEGER;
